"""add recipe tags cuisine meal_type cook_time

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-16 19:51:04.347642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cuisine', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('meal_type', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'cook_time_minutes')
    op.drop_column('recipes', 'meal_type')
    op.drop_column('recipes', 'cuisine')
    # ### end Alembic commands ###
